version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8082"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"

  order-service:
    build: ./order-service
    ports:
      - "8085:8085"

  payment-service:
    build: ./payment-service
    ports:
      - "8086:8086"

  product-service:
    build: ./product-service
    ports:
      - "8087:8087"
