version: "3.9"

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - auth-db
    env_file:
      - .env.auth-db

  auth-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env.auth-db

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8082"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8083:8083"

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"

  order-service:
    build: ./order-service
    ports:
      - "8085:8085"

  payment-service:
    build: ./payment-service
    ports:
      - "8086:8086"

  product-service:
    build: ./product-service
    ports:
      - "8087:8087"
